---
listen:
  port: 5575
mysql:
  db: gin
  host: mysql
  port: 3306
  user: gin
  pass: 4fuWD7w3xELgVFm4VYJr
redis:
  host: redis
  port: 6379
  db: 1
  pass: pFG64SBbhGB56K8Cv5eZbrdQ
logfile: logs/gin.log