---
listen:
  port: 5575
mysql:
  db: gin
  host: mysql
  port: 3306
  user: gin
  pass: aCP9gUfPP7rZDd3eJ9FnbCbf
redis:
  host: redis
  port: 6379
  pass: pFG64SBbhGB56K8Cv5eZbrdQ
  db: 1
logfile: logs/gin.log
